apiVersion: v1
kind: PersistentVolume
metadata:
  name: pypi-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/packages"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypi-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi

---

apiVersion: v1
kind: Secret
metadata:
  name: pypisecret
type: Opaque
stringData:
  username: pypi # make sure to change username
  password: pass # make sure to change password